---
- name: create cron job under /etc/cron.d
  ansible.builtin.cron:
    name: ansible-pull
    minute: "0"
    user: root
    job: "/usr/bin/ansible-pull -U https://github.com/coyte/anspull -i hosts site.yml > /dev/null 2>&1"
    cron_file: ansible-pull


- name: disable cdrom apt repository
  lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: '^deb cdrom'

- name: install packages
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    pkg:
    - sudo
    - git
    - unattended-upgrades
    - systemd-journal-remote
    - qemu-guest-agent
    - mosh

- name: Install posix roles from Ansible Galaxy
  command: ansible-galaxy collection install ansible.posix
  args:
    creates: /usr/lib/python3/dist-packages/ansible_collections/ansible/posix

- name: create user
  ansible.builtin.user:
    name: niels
    shell: /bin/bash
    groups: sudo
    append: yes
    uid: 1026

#- name: nsabine SSH authorized_keys
#  ansible.posix.authorized_key:
#    user: nsabine
#    state: present
#    key: '{{ item }}'
#  with_file:
#    - files/nsabine.pub

- name: sudoers no passwd
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: start unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started