---
- name: display hostname
  debug: var={{ ansible_hostname }}

- name: install prerequisite packages
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates 
    - curl 
    - gnupg

- name: Add Docker repository key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: install Docker packages
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    pkg:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Add user to docker group
  ansible.builtin.user:
    name: niels
    groups: docker
    append: yes
