---
- name: display hostname
  debug: var={{ ansible_hostname }}

- name: install packages
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates 
    - curl 
    - gnupg

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: install packages
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    pkg:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin

# TODO: Make Docker accessible to ordinary users

